/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.Admin;

/**
 *
 * @author ahmet
 */
public class AlbumInsertionGUI extends javax.swing.JFrame {

    Admin admin = new Admin();
    AdminGUI adminGUI;
    private int status;
    private int id;
    
    /**
     * Creates new form AlbumInsertionGUI
     */
    public AlbumInsertionGUI(AdminGUI adminGUI, int id, int status) {
        this.adminGUI = adminGUI;
        this.id = id;
        this.status = status;
        initComponents();
        
        if(status == 1) {
            btnAdd.setText("Güncelle");
            setTitle("Albüm Güncelle");
        }
    }
    
    public AlbumInsertionGUI() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAlbumInsertion = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        fldDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblArtist = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        fldArtist = new javax.swing.JTextField();
        fldGenre = new javax.swing.JTextField();

        setTitle("Albüm Ekle");
        setLocation(new java.awt.Point(575, 250));

        pnlAlbumInsertion.setBackground(new java.awt.Color(153, 0, 153));

        lblName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Ad:");

        lblDate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Tarih:");

        fldName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldDate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnAdd.setText("Ekle");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N

        lblArtist.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblArtist.setForeground(new java.awt.Color(255, 255, 255));
        lblArtist.setText("Sanatçı:");

        lblGenre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblGenre.setForeground(new java.awt.Color(255, 255, 255));
        lblGenre.setText("Tür:");

        fldArtist.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldArtist.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldGenre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldGenre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnlAlbumInsertionLayout = new javax.swing.GroupLayout(pnlAlbumInsertion);
        pnlAlbumInsertion.setLayout(pnlAlbumInsertionLayout);
        pnlAlbumInsertionLayout.setHorizontalGroup(
            pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                                .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                        .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                                        .addComponent(lblArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fldArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(fldGenre)))))
                            .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlbumInsertionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAlbumInsertionLayout.setVerticalGroup(
            pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlbumInsertionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(fldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtist)
                    .addComponent(fldArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlbumInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenre)
                    .addComponent(fldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAlbumInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAlbumInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(status == 0) {
            boolean control = admin.insertAlbum(
                fldName.getText(),
                fldDate.getText(),
                Integer.parseInt(fldArtist.getText()),
                Integer.parseInt(fldGenre.getText()));

            if(control) {
                fldName.setText(null);
                fldDate.setText(null);
                fldArtist.setText(null);
                fldGenre.setText(null);
            }
        } else if(status == 1) {
            boolean control = admin.updateAlbum(
                    id, 
                    fldName.getText(), 
                    fldDate.getText(), 
                    Integer.parseInt(fldArtist.getText()),
                    Integer.parseInt(fldGenre.getText()));
            
            if(control) {
                fldName.setText(null);
                fldDate.setText(null);
                fldArtist.setText(null);
                fldGenre.setText(null);
            }
        }

        adminGUI.updateAlbumTable();
        adminGUI.updateSongTable();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumInsertionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField fldArtist;
    private javax.swing.JTextField fldDate;
    private javax.swing.JTextField fldGenre;
    private javax.swing.JTextField fldName;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlAlbumInsertion;
    // End of variables declaration//GEN-END:variables
}
