package GUI;

import Database.DbHelper;
import Objects.User;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ahmet
 */
public class LoginGUI extends javax.swing.JFrame {

    AdminGUI adminGUI = new AdminGUI();
    UserGUI userGUI;
    SignupGUI signupGUI = new SignupGUI();
    
    private DbHelper helper = new DbHelper();
    private Connection connection = null;
    private Statement statement = null;
    private ResultSet resultSet;
    
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlUserLogin = new javax.swing.JPanel();
        lblUserEmail = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        btnUserLogin = new javax.swing.JButton();
        fldUserEmail = new javax.swing.JTextField();
        fldUserPassword = new javax.swing.JPasswordField();
        cbUserLogin = new javax.swing.JCheckBox();
        lblUserWarning = new javax.swing.JLabel();
        lblSignup = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        pnlAdminLogin = new javax.swing.JPanel();
        lblAdminEmail = new javax.swing.JLabel();
        lblAdminPassword = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JButton();
        fldAdminUsername = new javax.swing.JTextField();
        fldAdminPassword = new javax.swing.JPasswordField();
        cbAdminLogin = new javax.swing.JCheckBox();
        lblAdminWarning = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soundguin Login");
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);

        pnlLogin.setBackground(new java.awt.Color(204, 0, 204));

        pnlUserLogin.setBackground(new java.awt.Color(153, 0, 153));

        lblUserEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUserEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblUserEmail.setText("E-mail:");

        lblUserPassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUserPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblUserPassword.setText("Parola:");

        btnUserLogin.setText("Giriş");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        fldUserEmail.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        fldUserEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldUserPassword.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        fldUserPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbUserLogin.setBackground(new java.awt.Color(153, 0, 153));
        cbUserLogin.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        cbUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        cbUserLogin.setText("Şifreyi Göster");
        cbUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUserLoginActionPerformed(evt);
            }
        });

        lblUserWarning.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUserWarning.setForeground(new java.awt.Color(255, 255, 255));
        lblUserWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserWarning.setText("Giriş Yap");

        lblSignup.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(255, 255, 255));
        lblSignup.setText("Hesabınız yok mu?");

        btnSignup.setText("Kaydol");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLoginLayout = new javax.swing.GroupLayout(pnlUserLogin);
        pnlUserLogin.setLayout(pnlUserLoginLayout);
        pnlUserLoginLayout.setHorizontalGroup(
            pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignup)
                .addContainerGap())
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(lblUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(fldUserPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUserLogin)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSignup)
                .addContainerGap())
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnUserLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserLoginLayout.setVerticalGroup(
            pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignup)
                .addGap(4, 4, 4)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup))
                .addGap(27, 27, 27)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(fldUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbUserLogin)
                        .addComponent(lblUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnUserLogin)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Kullanıcı Giriş", pnlUserLogin);

        pnlAdminLogin.setBackground(new java.awt.Color(153, 0, 153));

        lblAdminEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAdminEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminEmail.setText("Kullanıcı Adı:");

        lblAdminPassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAdminPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminPassword.setText("Parola:");

        btnAdminLogin.setText("Giriş");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        fldAdminUsername.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        fldAdminUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldAdminPassword.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        fldAdminPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbAdminLogin.setBackground(new java.awt.Color(153, 0, 153));
        cbAdminLogin.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        cbAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        cbAdminLogin.setText("Şifreyi Göster");
        cbAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdminLoginActionPerformed(evt);
            }
        });

        lblAdminWarning.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAdminWarning.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminWarning.setText("Giriş Yap");

        javax.swing.GroupLayout pnlAdminLoginLayout = new javax.swing.GroupLayout(pnlAdminLogin);
        pnlAdminLogin.setLayout(pnlAdminLoginLayout);
        pnlAdminLoginLayout.setHorizontalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdminEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(fldAdminPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAdminLogin)
                .addGap(14, 14, 14))
            .addComponent(lblAdminWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminLogin)
                .addGap(187, 187, 187))
        );
        pnlAdminLoginLayout.setVerticalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAdminWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdminEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(fldAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAdminLogin)
                        .addComponent(lblAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAdminLogin)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin Giriş", pnlAdminLogin);

        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select username, password from admin");
            String username = fldAdminUsername.getText();
            String password = String.valueOf(fldAdminPassword.getPassword());
            while(resultSet.next()) {
                if(username.equals(resultSet.getString("username"))
                        && password.equals(resultSet.getString("password"))) {
                    setVisible(false);
                    adminGUI.setVisible(true);
                } else {
                    lblAdminWarning.setText("Kullanıcı adı veya parola hatalı!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void cbUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUserLoginActionPerformed
        if(cbUserLogin.isSelected()) {
            fldUserPassword.setEchoChar((char)0);
        } else {
            fldUserPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_cbUserLoginActionPerformed

    private void cbAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdminLoginActionPerformed
        if(cbAdminLogin.isSelected()) {
            fldAdminPassword.setEchoChar((char)0);
        } else {
            fldAdminPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_cbAdminLoginActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from users");
            String email = fldUserEmail.getText();
            String password = String.valueOf(fldUserPassword.getPassword());
            while(resultSet.next()) {
                if(email.equals(resultSet.getString("email"))
                        && password.equals(resultSet.getString("password"))) {
                    setVisible(false);
                    User user = new User(
                        resultSet.getInt("id"), 
                        resultSet.getString("name"), 
                        resultSet.getString("sname"), 
                        resultSet.getString("email"),
                        resultSet.getString("password"),
                        resultSet.getInt("subscription"),
                        resultSet.getString("country")
                    );
                    userGUI = new UserGUI(user);
                    userGUI.setVisible(true);
                } else {
                    lblUserWarning.setText("E-mail veya parola hatalı!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        signupGUI.setVisible(true);
    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JCheckBox cbAdminLogin;
    private javax.swing.JCheckBox cbUserLogin;
    private javax.swing.JPasswordField fldAdminPassword;
    private javax.swing.JTextField fldAdminUsername;
    private javax.swing.JTextField fldUserEmail;
    private javax.swing.JPasswordField fldUserPassword;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdminEmail;
    private javax.swing.JLabel lblAdminPassword;
    private javax.swing.JLabel lblAdminWarning;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JLabel lblUserWarning;
    private javax.swing.JPanel pnlAdminLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlUserLogin;
    // End of variables declaration//GEN-END:variables
}
