/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.*;

/**
 *
 * @author ahmet
 */
public class SongInsertionGUI extends javax.swing.JFrame {

    Admin admin = new Admin();
    AdminGUI adminGUI;
    private int id;
    private int status;
    
    /**
     * Creates new form SongInsertionGUI
     */
    public SongInsertionGUI(AdminGUI adminGUI, int id, int status) {
        this.adminGUI = adminGUI;
        this.id = id;
        this.status = status;
        initComponents();
        
        if(status==1) {
            btnAdd.setText("Güncelle");
            setTitle("Şarkı Güncelle");
        }
    }
    
    public SongInsertionGUI() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSongInsertion = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        fldAlbum = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblPlays = new javax.swing.JLabel();
        fldDuration = new javax.swing.JTextField();
        fldPlays = new javax.swing.JTextField();

        setTitle("Şarkı Ekle");
        setLocation(new java.awt.Point(575, 250));
        setPreferredSize(new java.awt.Dimension(363, 400));
        setResizable(false);

        pnlSongInsertion.setBackground(new java.awt.Color(153, 0, 153));

        lblName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Ad:");

        lblAlbum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAlbum.setForeground(new java.awt.Color(255, 255, 255));
        lblAlbum.setText("Albüm:");

        fldName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldAlbum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldAlbum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnAdd.setText("Ekle");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N

        lblDuration.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblDuration.setText("Süre:");

        lblPlays.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblPlays.setForeground(new java.awt.Color(255, 255, 255));
        lblPlays.setText("Dinleme:");

        fldDuration.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fldPlays.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fldPlays.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnlSongInsertionLayout = new javax.swing.GroupLayout(pnlSongInsertion);
        pnlSongInsertion.setLayout(pnlSongInsertionLayout);
        pnlSongInsertionLayout.setHorizontalGroup(
            pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                        .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlays, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fldAlbum)
                            .addComponent(fldDuration)
                            .addComponent(fldPlays)
                            .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        pnlSongInsertionLayout.setVerticalGroup(
            pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongInsertionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(3, 3, 3)
                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSongInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldPlays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlays))
                .addGap(43, 43, 43)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSongInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSongInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Album album = admin.getAlbum(Integer.parseInt(fldAlbum.getText()));
        if(status==0) {
            boolean control = admin.insertSong(
                fldName.getText(),
                album.getDate(),
                album.getArtistID(),
                Integer.parseInt(fldAlbum.getText()),
                album.getGenreID(),
                fldDuration.getText(),
                Integer.parseInt(fldPlays.getText()));

            if(control) {
                fldName.setText(null);
                fldAlbum.setText(null);
                fldDuration.setText(null);
                fldPlays.setText(null);
            }
        } else if(status==1) {
            boolean control = admin.updateSong(
                id,
                fldName.getText(),
                album.getDate(),
                album.getArtistID(),
                Integer.parseInt(fldAlbum.getText()),
                album.getGenreID(),
                fldDuration.getText(),
                Integer.parseInt(fldPlays.getText()));

            if(control) {
                fldName.setText(null);;
                fldAlbum.setText(null);
                fldDuration.setText(null);
                fldPlays.setText(null);
            }
        }
        
        adminGUI.updateSongTable();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SongInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SongInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SongInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SongInsertionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SongInsertionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField fldAlbum;
    private javax.swing.JTextField fldDuration;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldPlays;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlays;
    private javax.swing.JPanel pnlSongInsertion;
    // End of variables declaration//GEN-END:variables
}
